---
- hosts: all
  tasks:
    - name: Install Git, wget, curl
      apt: name={{ item }} state=present
      with_items:
        - git
        - wget
        - curl
        - fail2ban
        - nginx
        - mariadb

    - name: Enable  Fail2Ban, mariadb, nginx daemon
      service: name={{ item }} state=started enabled=yes
      with_items:
        - fail2ban
        - mariadb 
        - nginx